# Generated by Django 6.0 on 2025-12-30 13:01

from django.db import migrations


def set_verified_users_onboarded(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(is_email_verified=True).update(is_onboarded=True)


def reverse_onboarded(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.update(is_onboarded=False)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_is_onboarded_field"),
    ]

    operations = [
        migrations.RunPython(set_verified_users_onboarded, reverse_onboarded),
    ]
